### ISSUE TITLE
provider verify local pacts failed

### ISSUE THREAD

**Issue by iamhuahua** [zachallen/pact-java#1]
I operate according to the document. The pacts created successfully, then I execute mvn pact:verify ,failed.
The error is: No plugin found for prefix 'pact' in the current project and in the plugin groups [org.apache.maven
.plugins, org.codehaus.mojo] available from the repositories

I did not use pact broker,and I want to verify local pacts.Please help me

**Comment by zachallen** [comment]
I've updated the plugin and readme. Give it another try now

**Comment by iamhuahua** [comment]
ok

**Comment by iamhuahua** [comment]
Please tell me how do you think of updating pact-jvm-provider-maven_2.11 to pact-jvm-provider-maven? I am new to Pact,and want to learn the ways of solving problems.thank you

**Comment by iamhuahua** [comment]
I update the pom.xml of  pact-provider :pact-jvm-provider-maven version to the following, mvn pact:verify succeed:
                <groupId>au.com.dius</groupId>
                <artifactId>pact-jvm-provider-maven_2.12</artifactId>
                <version>3.5.23</version>
